# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r32FEl8hDOsNEItiarp7J6WhXvX_-W6t
"""

import streamlit as st
import joblib
import numpy as np
from google.colab import drive
from sklearn.metrics.pairwise import cosine_similarity
drive.mount('/content/drive')

st.set_page_config(page_title="Risk Assessment BPJSTK", layout="wide")

@st.cache_resource
def load_backend():
    path = "/content/drive/MyDrive/BPJSTK/backend.joblib"
    data = joblib.load(path)
    return data

from google.colab import drive
drive.mount('/content/drive')

try:
    data = load_backend()
    m1 = data['m1']
    m2 = data['m2']
    DAMPAK_ORDER = data['DAMPAK_ORDER']
    DAMPAK_LABEL = data['DAMPAK_LABEL']
    KEMUNGKINAN_LABEL = data['KEMUNGKINAN_LABEL']
    BATAS_SELERA = data['BATAS_SELERA']
    AREA_DAMPAK_MAP = data['AREA_DAMPAK_MAP']
    st.success("Berhasil memuat model")
    print("Good")
except Exception as e:
    st.error(f"Gagal memuat model: {e}")
    st.stop()
    print("Bad")

def get_risk_color(dampak, kemungkinan):
    score = (DAMPAK_ORDER.index(dampak) + 1) * kemungkinan
    if score <= 4:    return "#4CAF50", "Rendah"
    elif score <= 9:  return "#FFEB3B", "Sedang"
    elif score <= 16: return "#FF9800", "Tinggi"
    else:             return "#F44336", "Sangat Tinggi"

st.title("🛡️ Sistem Prediksi Risiko & Dampak")
st.markdown("---")

col1, col2 = st.columns([1, 1], gap="large")

with col1:
    st.subheader("1. Identifikasi Konteks & Kategori")
    tujuan_input = st.text_area("Tujuan Aktivitas", placeholder="Contoh: Mengelola data peserta untuk program JHT...")

    st.write("**Kriteria (Checklist jika ada):**")
    selected_criteria = {}
    # Mengambil kolom kriteria dari model m1
    for crit in m1["criteria_columns"]:
        selected_criteria[crit] = st.checkbox(crit)

    st.subheader("2. Penilaian Kemungkinan")
    probabilitas = st.select_slider(
        "Skala Kemungkinan (1-5)",
        options=[1, 2, 3, 4, 5],
        format_func=lambda x: f"{x} - {KEMUNGKINAN_LABEL[x]}"
    )

with col2:
    st.subheader("3. Analisis Dampak")
    area_dampak_display = st.selectbox("Pilih Area Dampak", list(AREA_DAMPAK_MAP.keys()))
    area_dampak_internal = AREA_DAMPAK_MAP[area_dampak_display]

    teks_dampak = st.text_area("Deskripsi Kejadian Dampak", placeholder="Contoh: Terjadi kebocoran data NIK sebanyak 1000 user...")

    st.markdown("---")
    btn_predict = st.button("🚀 Jalankan Prediksi Risiko", use_container_width=True)

# --- LOGIC PREDIKSI ---
if btn_predict:
    if not tujuan_input or not teks_dampak:
        st.warning("Mohon isi Tujuan dan Deskripsi Dampak terlebih dahulu.")
    else:
        # 1. Build Context untuk Kategori Risiko
        # Simulasi baris dataframe untuk fungsi build_context
        row_sim = {"TUJUAN": tujuan_input}
        for k, v in selected_criteria.items():
            row_sim[k] = "ada" if v else "tidak ada"

        # Build context menggunakan fungsi dari m1/backend
        # (Karena fungsi build_context ada di predictmodel.py, kita tulis ulang di sini atau panggil jika sudah masuk backend)
        context = f"Tujuan aktivitas ini adalah: {tujuan_input}. "
        active = [k for k in selected_criteria if selected_criteria[k]]
        if active:
            context += "Aktivitas ini memiliki beberapa karakteristik berikut: "
            for k in active:
                context += f"aktivitas ini melibatkan {k}. "
        context += "Aktivitas ini dapat menimbulkan risiko terhadap pengguna."

        # 2. Prediksi Kategori (Top 1)
        emb_context = m1["model"].encode([context])
        emb_tujuan  = m1["model"].encode([tujuan_input])
        final_emb   = (0.5 * emb_context) + (0.5 * emb_tujuan)
        fin_sim     = cosine_similarity(final_emb, m1["kamus_embeddings"])[0]
        idx_kategori = fin_sim.argmax()
        kategori_pred = m1["kamus"].iloc[idx_kategori]["Kategori Risiko"]
        conf_kategori = fin_sim[idx_kategori]

        # 3. Prediksi Skala Dampak (m2)
        subset_dampak = m2["kamus_dampak"][m2["kamus_dampak"]["Area Dampak"] == area_dampak_internal].reset_index(drop=True)
        emb_input_dampak = m2["model"].encode([teks_dampak])
        sim_dampak = cosine_similarity(emb_input_dampak, m2["dampak_embeddings"][area_dampak_internal])[0]
        idx_d = sim_dampak.argmax()

        skala_d = subset_dampak.iloc[idx_d]["Skala"]
        deskripsi_d = subset_dampak.iloc[idx_d]["Deskripsi"]
        jenis_d = subset_dampak.iloc[idx_d]["Jenis Dampak"]

        # 4. Hitung Skor & Batas Selera
        color, level = get_risk_color(skala_d, probabilitas)

        # --- DISPLAY HASIL ---
        st.success("### Hasil Analisis")

        res_col1, res_col2, res_col3 = st.columns(3)

        with res_col1:
            st.metric("Kategori Risiko Prediksi", kategori_pred)
            st.caption(f"Confidence Score: {conf_kategori:.2%}")

        with res_col2:
            st.metric("Skala Dampak", f"{skala_d} ({DAMPAK_LABEL[skala_d]})")
            st.info(f"**Jenis:** {jenis_d}\n\n**Ref:** {deskripsi_d}")

        with res_col3:
            st.markdown(f"""
                <div style="background-color:{color}; padding:20px; border-radius:10px; text-align:center;">
                    <h3 style="color:white; margin:0;">Tingkat Risiko</h3>
                    <h1 style="color:white; margin:0;">{level}</h1>
                </div>
            """, unsafe_allow_html=True)

        # 5. Cek Batas Selera
        if kategori_pred in BATAS_SELERA:
            batas = BATAS_SELERA[kategori_pred]
            aktual_angka = (DAMPAK_ORDER.index(skala_d) + 1) * probabilitas
            status_selera = "🔴 MELEBIHI BATAS" if aktual_angka > batas["angka"] else "🟢 DALAM BATAS"

            st.markdown("---")
            st.subheader("Pengecekan Batas Selera Risiko")
            bs_col1, bs_col2, bs_col3 = st.columns(3)
            bs_col1.write(f"**Batas Maksimal:** {batas['peta']} (Skor: {batas['angka']})")
            bs_col2.write(f"**Skor Aktual:** {aktual_angka}")
            bs_col3.write(f"**Status:** {status_selera}")